version: '3.8'

services:
  actix-api:
    build: .
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - PORT=3333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s