name: Shuttle Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'api-shuttle/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01K49V83RHT96FEVNY5A3YZQAZ
          working-directory: "api-shuttle"
          cargo-shuttle-version: "0.52.0"
          extra-args: --allow-dirty --debug
          secrets: |
            DATABASE_URL = '${{ secrets.DATABASE_URL }}'